### ISSUE TITLE
Ordering of COSD Data Sets

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#63] opened 2020-04-01 15:26 UTC
DataSets: cancer outcomes and services data set:
- Core should be at the top of the list, rather than being in alphabetical order

**Comment by AngelaFaulding** [comment] 2021-01-13 10:18
This is OK on the introduction page but not on the menu

**Comment by AngelaFaulding** [comment] 2021-05-05 07:54
Menu still not in the correct order, see https://www.datadictionary.nhs.uk/data_sets/clinical_data_sets/cosds/cancer_outcomes_and_services_data_set_-_core.html

**Comment by AngelaFaulding** [comment] 2021-05-17 13:50
James will investigate when we migrate for:
https://www.datadictionary.nhs.uk/data_sets/clinical_data_sets/cosds.html
https://www.datadictionary.nhs.uk/data_sets/clinical_content/national_joint_registry_data_set.html
https://www.datadictionary.nhs.uk/data_sets/supporting_data_sets.html
https://www.datadictionary.nhs.uk/data_sets/cds_v6-2.html

**Comment by AngelaFaulding** [comment] 2021-12-10 06:27
10/12/21 - should be able to do this in the data set folder when we have migrated to Mauro

**Comment by AngelaFaulding** [comment] 2022-04-01 11:12
Issue closed as it is a duplicate of #392

**Closed by AngelaFaulding** 2022-04-01 11:12 UTC
Labels: Data Sets, 3++, Navigation, OXFORD, DMDS, Post Migration, Dev (M)
