### ISSUE TITLE
Emails not being issued

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#487] opened 2024-07-15 11:28 UTC
Currently emails are failing when users are added to Mauro or the password has been reset.
Will the "Date/Time" column be populated when the email issue is fixed.

![image](https://github.com/user-attachments/assets/ceb9c9a9-b352-4b36-bcc4-48574162b0c9)

**Comment by pjmonks** [comment] 2024-07-15 11:56
Currently you do not have a SMTP server setup yet on Mauro to actually send emails, this is a delay caused by your NHS networking team. Please check with Steve Bowring of when the status of this will be unblocked.

**Comment by AngelaFaulding** [comment] 2024-07-15 12:00
OK but will the "Date/Time" column be populated when we have a SMTP server setup?

**Comment by AngelaFaulding** [comment] 2024-07-29 07:17
Peter has demonstrated this but it still doesn't work for us.
@GSChandel - I have put this in the backlog but feel free to move it to where you think it should be.

**Comment by NellySSJ** [comment] 2024-11-15 15:02
Closing - SMTP function won't be setup. We will be using OpenID to login using Single Sign On. In addition, SMTP function stores the email (with password) that is sent to the user, and has been flagged by Cyber as a significant risk.

**Closed by NellySSJ** 2024-11-15 15:02 UTC
Labels: 2024 - MS02: User Administration
