### ISSUE TITLE
Missing tables

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#5] opened 2020-04-01 13:16 UTC
HTML Table temporarily redacted is no longer displayed but the tables are missing

**Comment by cach1** [comment] 2020-09-22 12:44
Does this relate to AREA OF WORK NAME table?

**Comment by AngelaFaulding** [comment] 2020-09-29 13:17
I will remove the National Codes heading and the links on the Data Elements as these are not National Codes.
This will be done in the October release

Maxine - will this resolve your issue?

**Comment by maxChappell** [comment] 2020-09-29 13:36
Issue already resolved from our end (likin pipe) - mauro processes whether on ontoserver or not appropriately.

**Comment by maxChappell** [comment] 2020-10-19 11:06
Question for @oughnic and @cach1 - do we care that historic fhir items for this are not available on ontoserver? Or should we create this items' history by creating some bespoke code?

**Comment by oughnic** [comment] 2020-10-20 07:30
Assuming its area of work, I'm not inclines to invest extra effort here.

**Comment by AngelaFaulding** [comment] 2020-11-05 07:34
This has been fixed by removing the National Codes header on the Attribute as the table doesn't contain National Codes.
The table is appearing on the Data Element, I wasn't expecting that. Is that what was intended?

**Comment by maxChappell** [comment] 2020-11-05 10:07
Gaps in historic fhir content will by identified via db queries and business will make decisions on where/whether to invest effort to fill the historic gaps. So happy to now close this.

**Closed by maxChappell** 2020-11-05 10:07 UTC
Labels: 3+, Attributes, October 2020 release, Ontoserver
